Make use of environmental variables for superuser creation
evennia/evennia pull request #2306
Opened 2021-01-16 16:14 UTC by srmeier

#### Brief overview of PR changes/additions
When superuser is created pull details from environmental variables so that no interaction is required. If environmental variables are not present then fallback to typical behavior.

#### Motivation for adding to Evennia
Very helpful when launching via Docker (see feature request #2248).

#### Other info (issues closed, discussion etc)
I am not sure to what extent we would like this to mimic Django's support (see [here](https://docs.djangoproject.com/en/3.1/ref/django-admin/#createsuperuser)). The approach I have proposed here looks for both a username AND email address first, and then will check to see if an environmental variable for the password is present. Django's `createsuperuser` command does not allow for setting the password programmatically so I am leveraging `evennia.accounts.models.AccountDB` to perform that operation.

2021-01-18 21:02 UTC, Griatch requested changes
This is a fine idea, but reviewing and testing this I find a few points that need improvement: 

- Might as well name these envvars `EVENNIA_SUPERUSER_*` instead. While it's true that they are used by Django under the hood, django knowledge is not strictly needed (so it's just confusing) and they are only ever useful for the `evennia` launcher anyway.
- The `..SUPERUSER_EMAIL` should not be a required envvar. If not given, this should be assumed to be left blank. This reflects how you can just press `<return>` to bypass this input when doing the interactive setup. 
- Trying to not specify the email by giving `..SUPERUSER_EMAIL=` or `=""` currently gives an error: `django.core.management.base.CommandError: You must use --email with --noinput.`

2021-01-18 22:36 UTC, srmeier commented
Sounds good 👍 , Added a few changes to address the points above. Currently is the password required?

2021-01-21 13:25 UTC, Griatch commented
> Sounds good , Added a few changes to address the points above. Currently is the password required?

Haven't tested this yet, but to answer your question - the superuser password should not be allowed to be empty. So if this is missing, this should be handled gracefully rather than triggering a traceback.

2021-01-23 04:08 UTC, srmeier commented
> Haven't tested this yet, but to answer your question - the superuser password should not be allowed to be empty. So if this is missing, this should be handled gracefully rather than triggering a traceback.

Thanks, I have added a check for the password. If either the username or the password environmental variables are missing then current logic is to fallback to the standard process of interactively requesting that the user enter them.

`os.environ.get('EVENNIA_SUPERUSER_EMAIL')` Will check for the email environmental variable and if it is missing it will pass `None` as the email arguement to the `AccountDB.objects.create_superuser()` function (which is the default for that function anyways).

I wouldn't expect anything here to trigger a stack trace

2021-01-23 04:24 UTC, srmeier commented
Made the code a little more clear and I am also now explicitly checking to make sure the length of the password is greater than 0.

2021-01-30 12:14 UTC, Griatch approved these changes
Thanks for the changes!

2021-01-30 12:14 UTC, merged