delay docstring update
evennia/evennia pull request #2412
Opened 2021-05-10 16:41 UTC by davewiththenicehat

delay docstring update

The old one had not been properly updated or formatted.

#### Brief overview of PR changes/additions
An update to utils.delay's docstring

#### Motivation for adding to Evennia
I had it formatted incorrectly. Also it's return message was incorrect.

#### Other info (issues closed, discussion etc)

2021-05-10 19:38 UTC, Griatch requested changes
Not sure why you moved this text up from the `Note` to the top of the function?

2021-05-10 19:38 UTC, Griatch commented on evennia/utils/utils.py
> +        All task's whose time delays have passed will be called on server startup.
This sounds like it belongs partly in the `persistent` arg description and in a `Notes` section.

2021-05-10 19:38 UTC, Griatch commented on evennia/utils/utils.py
> +        any (any, optional): Will be used as keyword arguments to callback.
It's actually OK to just put `any:` I think.

2021-05-10 21:10 UTC, davewiththenicehat commented
What tool is being used to generate the documentation?
I think I got the kwargs section incorrect also.

I'm happy to read up on it. I don't know where to look this up. The google style docstring documentation I was able to find did not show 'Notes' as a header type so I removed it.

2021-05-10 21:14 UTC, Griatch commented
We use sphinx with the Napoleon parser. Easiest is probably to look at existing Evennia docstrings, but the Napoleon parser is documented here: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

2021-05-11 18:08 UTC, Griatch commented
As far as I can tell the existing doc string was fine, so closing this.

2021-05-11 20:27 UTC, davewiththenicehat commented
delay does not return a deferred or int. It returns a TaskHandlerTask instance.

2021-05-11 21:48 UTC, merged