Adding "mult" to traits contrib
evennia/evennia pull request #2628
Opened 2022-01-15 07:10 UTC by Tegiminis

#### Brief overview of PR changes/additions

Adds "mult" as a stat to the traits contrib, allowing developers to use multiplicative modifiers for their traits. Anywhere that you would receive "base + mod" as a return has been edited to "(base + mod) * mult". This is the current value for Static and Counter traits, and the max value for Gauge traits.

#### Motivation for adding to Evennia

I use multiplicative math for my game's buffs and stats sometimes, so I figure other people might too.

2022-01-19 10:43 UTC, Griatch requested changes
Thanks for the change! The docstrings for each of the Trait classes must be updated as well though, since these don't mention the multiplier anywhere today and you'd have to read the code to find out it exists. 
It would also be good to see a new unit per trait class to show that this behaves as expected.

2022-01-19 20:58 UTC, Tegiminis commented
Updated with documentation that reflects the change as well as properly utilizing multiplier in validation and string methods. Will start on some unit tests.

2022-01-20 21:30 UTC, Griatch requested changes
Thanks for the additions. :) I only have some minor comments.

2022-01-20 21:30 UTC, Griatch commented on evennia/contrib/rpg/traits/traits.py
> +The static trait has a `base` value and an optional `mod`-ifier and 'mult'-iplier. A typical use
Worth pointing out that `mult` defaults to `1.0` and can thus be ignored if you don't need it.

2022-01-20 21:30 UTC, Griatch commented on evennia/contrib/rpg/traits/traits.py
> +                                             * mult
This looks wrong since it lacks the parenthesis; it looks like mod * mult. Better reformat it to use the parenthesis.

2022-01-20 21:30 UTC, Griatch commented on evennia/contrib/rpg/traits/traits.py
> +by multiplying by the multiplier. The min/max of the range are optional, a boundary
Again worth to note that `mult` defaults to 1.0.

2022-01-20 21:30 UTC, Griatch commented on evennia/contrib/rpg/traits/traits.py
> +                                              * mult
Same here, best to reformat to include the parenthesis.

2022-02-12 12:49 UTC, Griatch commented
@Tegiminis Any progress with the last changes to this?

2022-03-04 18:51 UTC, Griatch approved these changes
Thanks for the changes!

2022-03-04 18:52 UTC, merged