[Bugfix] 2736 Allow cmdsets to remove and retrieve by key
evennia/evennia pull request #2755
Opened 2022-06-07 16:32 UTC by ChrisLR

#### Brief overview of PR changes/additions
This allows removing and retrieving commands in a CmdSet by using the key

#### Motivation for adding to Evennia
Fixing bugs

#### Other info (issues closed, discussion etc)
It introduces the commands_by_key dict to avoid iterating over all cmds anytime you want to refer to one by key.

I also changed the add's handling of the remove duplicates as it seemed to be  removing duplicates at every iteration instead of just once at the end.

2022-06-20 19:11 UTC, Griatch requested changes
I don't see why this complexity is needed in order to implement this ... you now have two parallel stores (`.commands` and `.commands_by_key`) that must be maintained separately and which could theoretically go out of sync with one another. 

It would seem much simpler to just implement changes in `remove` and `get` methods here and simply loop over the commands to see if a key matches - potentially caching the result as an optimization.

2022-06-20 19:58 UTC, ChrisLR commented
@Griatch true, I was gradually aiming at replacing .commands to only use .commands_by_key, since we'll be iterating all the time, why not simply get by key all the time... but yeah I don't mind I'll make the change

2022-06-21 06:09 UTC, Griatch commented
@ChrisLR It's not going to be used all the time; there is a reason noone noticed this missing - all internal operations are done by-command instance. The main use of this is as a convenience when you manually remove a default command in `default_cmdsets`.

2022-06-27 16:49 UTC, ChrisLR commented
I meant we iterate over commands often, while every command has a key.. it makes sense to retrieve by key internally.
Anyway, it can wait (or just not be done)

2022-06-27 16:51 UTC, ChrisLR commented on evennia/commands/cmdset.py
> +
This was originally nested, so it would try to make it unique multiple times, this will only do it once at the end.

2022-07-03 10:01 UTC, Griatch commented
@ChrisLR Thanks for the change! It looks like the unit tests are not passing here though, and it's cmd-related.

2022-07-24 06:34 UTC, Griatch commented
@ChrisLR As a reminder, the unit tests still don't pass on this.

2022-07-24 14:46 UTC, ChrisLR commented
@Griatch sorry for the delay, RL getting in the way again.

2022-08-02 10:58 UTC, merged

2022-08-02 13:22 UTC, Griatch commented
@ChrisLR As this was merged, it appears to have introduced a regression: The `NO_INPUT` syscommand stopped working; for example you can't accept deleting an object in-game (e.g. `del box? [yes]/no?` prompt) just by pressing `<return>` anymore. 
Not sure why this PR would cause this, but I stepped back in GIT history and the functionality returns if checking out a PR just before merging this particular PR. Will inevestigate further later.

2022-08-02 14:07 UTC, Griatch commented
For  completeness: The regression was resolved.