AttributeProperty tries spawning child instances of default value (#2697)
evennia/evennia pull request #2824
Opened 2022-08-02 23:51 UTC by strikaco

#### Brief overview of PR changes/additions
Makes AttributeProperty try using default value as a factory.

#### Motivation for adding to Evennia
Lets dev use lambdas or other callables as default value.

#### Other info (issues closed, discussion etc)
#2697

2022-08-04 10:35 UTC, Griatch requested changes
Thanks for the PR! While I'm not convinced the issue in #2697 is really a bug, I think it would be nice to support a callable factory for the utility of it. I have some comments on the implementation below.

2022-08-04 10:35 UTC, Griatch commented on evennia/typeclasses/attributes.py
> +            return self.__default
Never use a 'bare' `except` like this, it's frowned upon in PEP8 standard and is not considered good practice  (always use at least `except Exception`). 

But in this case I think it's also rather motivated to do a `callable` check here instead; it's probably more likely to not have a callable than having one, and relying on catching the exception every time is comparably expensive (even if 50% are callable, it's still about 10x faster to check `callable()` than to use `try...except` here). 

```python 
if callable(self.__default):
    return self.__default()
else:
    return self.__default
```

2022-08-05 19:49 UTC, strikaco commented
Just noticed there's a stray arg in there I decided not to use. Correction pending.

2022-08-14 14:45 UTC, Griatch approved these changes

2022-08-14 14:45 UTC, merged