Documentation fix for mobile/small screens
evennia/evennia pull request #2894
Opened 2022-10-03 03:21 UTC by audiodude

#### Brief overview of PR changes/additions

Documentation fix. Removes `position: absolute` from search results when screen is smaller than 960px, so they aren't broken on mobile. Also removes min-width on screens smaller than 960px, so that pages in general don't trail off the screen. Fix minor `height:88` bug, which was broken CSS and being ignored anyways.

See these changes here: https://evennia-doc-develop.netlify.app/

#### Motivation for adding to Evennia

Fixing bug.

#### Other info (issues closed, discussion etc)

Fixes #2741.

2022-10-03 18:21 UTC, Griatch requested changes
Thanks for the PR! Testing this, I see some issues with it though: 
- On the desktop, the `search` section seems entirely absent from the sidebar (Firefox 105)
![DeepinScreenshot_select-area_20221003201425](https://user-images.githubusercontent.com/294267/193649283-d04ace76-1ab8-4e1f-b90e-97972e27050f.png)
- On my phone (Chrome on Android), the text now looks better, but the search field (here it's still visible) is hovering in the middile of the screen, above the text ...
![Screenshot_20221003-201839_Chrome](https://user-images.githubusercontent.com/294267/193650069-c3d28209-f349-4864-b557-b3567c8abadc.jpg)

2022-10-03 23:28 UTC, audiodude commented
I can't reproduce the first bug you're seeing (missing search on sidebar). Is this from visiting https://evennia-doc-develop.netlify.app/ or did you build the docs yourself?

2022-10-03 23:33 UTC, audiodude commented
The searchbox is dynamically shown (for some reason) by Javascript using jQuery. Are you sure you have Javascript enabled and can you check for Javascript errors in the Firefox console? Make sure that the jQuery script loaded correctly.

2022-10-04 00:15 UTC, audiodude commented
I pushed a commit that fixes the phantom search bar, but unfortunately that leads to a new bug which I would call "Cannot search at all on mobile".

I'm going to try a more major surgery to make the site basically responsive, at least with regards to the sidebar and main content.

2022-10-04 01:07 UTC, audiodude commented
Okay with the latest round of changes, the site has a basic level of responsiveness. Some additional sizing and padding issues have also been fixed. PTAL!

2022-10-06 21:21 UTC, Griatch commented
Thanks for taking a second pass at it. :) It looks good to me now (the missing search field was indeed a script blocker running for that page). :+1:

2022-10-06 21:21 UTC, Griatch approved these changes

2022-10-06 21:21 UTC, merged