fix: improve convert_urls
evennia/evennia pull request #2897
Opened 2022-10-03 18:56 UTC by selberhad

#### Brief overview of PR changes/additions
- Adds a boundary character `\b` before URLs to cut down on false positives.
- Prefixes urls without a protocol with `//` to prevent browsers opening them as relative links on the webclient's domain. (Maybe this should just be `https://` rather than using the protocol-relative `//`? Opinions welcome!)
- Updates tests for urls without protocols, removes leading-w test, adds new test for boundary character requirement

#### Motivation for adding to Evennia
- Links of the form "www.example.com" currently open relative to the webclient URL, which is not expected behavior.
- Cuts down on false positives by requiring a non-word character before a url, so `www.example` will turn into a link on its own, but it won't highlight it in `Awww.example is cute`.

#### Other info (issues closed, discussion etc)
Relates to #2883, #1974

2022-10-06 21:29 UTC, Griatch requested changes
This looks like a good change. I'm not really sure about the `//` prefix. I'd think a full `http://` or `https://` prefix looks more solid ... but I don't have a super-strong opinion about it, so I'm open for debate. :)

2022-10-07 02:53 UTC, selberhad commented
Since we are essentially guessing what the protocol should be when the user hasn't provided one, there's no definitive best choice. Some points to consider:
1. Most (but not all) webservers will automatically upgrade `http` to `https` if they support secure connections
2. Conversely, webservers that only support `http` will time out if issued an `https` request
3. The vast majority of websites now support TLS (https) thanks to [LetsEncrypt](https://letsencrypt.org/)

My inclination would be to use `http`, but cybersecurity professionals would disagree 😁 . If a web server supports both but doesn't automatically upgrade connections, all modern browsers will at least indicate that the connection is 'Not Secure' for `http` requests, which seems better than just having the request time out for `https` requests if the server doesn't support TLS. That said, due to point 3, 99.9% of websites will work with `https` so either choice would probably be fine.

2022-10-08 02:25 UTC, selberhad commented
Hmm, not too sure what's going on with the merge here... will try to fix it up.

2022-10-09 08:57 UTC, Griatch approved these changes
Some good points there, and I agree - a `http` prefix seems like it would break the least :) Thanks for the fixes!

2022-10-09 08:57 UTC, merged