Update objects.py
evennia/evennia pull request #2898
Opened 2022-10-03 20:18 UTC by VexiaOnline

#### Brief overview of PR changes/additions

Simply changes self.key to self.name so that if get_numbered_name isn't overridden in the call, it will use the name property instead of key, this brings thing in line with other areas, so colorized object names can persist in get_numbered_name.

#### Motivation for adding to Evennia

I believe this is the only place that uses .key instead of .name, and I wanted the consistency of using .name so that other areas didn't need to be overridden to display object name colorization etc.

#### Other info (issues closed, discussion etc)

Not sure why it said before that my develop was behind main one, hopefully this time things are in sync?

2022-10-06 21:32 UTC, Griatch requested changes

2022-10-06 21:32 UTC, Griatch commented on evennia/objects/objects.py
> +        key = kwargs.get("key", self.name)
This change needs to be mentioned on line 1240 too - explaining that if `key` is not given, the `.name` property will be used instead.

2022-10-09 08:59 UTC, Griatch commented
@VexiaOnline Ping, since I know you may not be keeping an eye on this :)

2022-10-09 20:01 UTC, VexiaOnline commented
I haven not forgotten about this,  just on a plane to glorious Sweden, I will look and make the changes when I get settled in and my laptop set up. :)

2022-10-28 12:20 UTC, Griatch commented
@VexiaOnline Ping, and probably the last chance to have this count for Hacktoberfest :)

2022-11-18 11:28 UTC, merged

2022-11-18 11:28 UTC, Griatch commented
@VexiaOnline I merged this and added the requested doc string myself instead :)