Update comms.py
evennia/evennia pull request #2954
Opened 2022-10-25 23:24 UTC by homeofpoe

Extend fstring usage for consistency and clarity.

2022-10-26 17:17 UTC, Griatch requested changes
Lookin' good, just one typo to address.

2022-10-26 17:17 UTC, Griatch commented on evennia/commands/default/comms.py
> +        logger.log_sec("fChannel {channel_key} was deleted by {caller}")
`f` is inside the string.

2022-10-27 16:42 UTC, homeofpoe commented
Thanks!  Future PRs shouldn't have this problem.

2022-10-27 18:12 UTC, Griatch approved these changes

2022-10-27 18:12 UTC, merged