Use filter_family instead of filter
evennia/evennia pull request #3113
Opened 2023-02-13 16:10 UTC by blongden

#### Brief overview of PR changes/additions

Changing the use of filter to filter_family in search_channel

#### Motivation for adding to Evennia

It's possible to create a channel using a custom typeclass, however you cannot search for the channel once it's created using the current functionality. This change allows search_channel to find the channel once it's been created.

#### Other info (issues closed, discussion etc)

2023-02-13 17:49 UTC, blongden commented
Ok so this is the wrong fix. It does actually work though in game, however it fails with 'filter_family' not found on class ChannelDBManager in the tests or when using the evennia.search_channel python command. I have no idea why it would work in one scenario (when using the channel <name> <text> syntax to write to the channel) but not the others. Maybe one for discussion.

2023-02-13 18:20 UTC, blongden commented
This change appears to work and keeps the tests happy. I can't vouch for it's correctness though so please take a look! :)

2023-02-14 09:17 UTC, blongden commented
This is also the wrong fix here. It causes issues with logging in (not captured by tests yet).

```
evennia.comms.models.ChannelDB.MultipleObjectsReturned: get() returned more than one ChannelDB -- it returned 3!
```

2023-02-25 08:14 UTC, Griatch requested changes
I would suggest making the unit tests for the case you want to test first (including the login case not covered by unit tests - nice catch). Once those tests are in place you can check solutions. 

If you don't have time to address this, please make a formal ticket, explaining the issue in detail and how to reproduce.

2023-03-27 20:47 UTC, Griatch commented
Ping :)

2023-05-07 18:57 UTC, Griatch commented
@blongden This has not seen any changes or replies for 3 months, so I'm closing this. Feel free to ping me if you want to keep updating this and I'll be happy to reopen.

2023-05-07 18:57 UTC, closed without merging