Avoid moving an object to itself
evennia/evennia pull request #3127
Opened 2023-03-03 19:56 UTC by InspectorCaracal

#### Brief overview of PR changes/additions
At the moment, attempting to use `obj.move_to(somewhere)` when `somewhere` happens to be the same as `obj` will throw a runtime error, which is not caught.

This adds an explicit check before beginning the move hooks so that the move will instead fail gracefully.

#### Motivation for adding to Evennia
Better error handling

2023-03-03 20:36 UTC, InspectorCaracal commented
Looks like the test runner is still having trouble completing some of the test runs, but the PR itself didn't break any tests.

2023-03-04 17:42 UTC, Griatch requested changes
Hm, the `RuntimeError` is the correct response to prevent a location loop. We shouldn't add another superfluous check to check what the traceback is already reporting. 

If we want to make an error report here, we should catch the exception instead. Not only will this handle this case, but also any nested assignment (like trying to move and object to an object which is inside another object inside another object inside the moving object etc).

2023-03-04 18:21 UTC, InspectorCaracal commented
@Griatch Ahh, okay! I didn't know you could/had to catch runtime errors separately from exceptions, so I figured since it isn't caught by the current try/except it wasn't catchable.

I'll update the PR

2023-03-04 18:39 UTC, Griatch commented
A `RuntimeError` is just another exception :)

2023-03-04 18:42 UTC, Griatch requested changes
Well, if the original `Exception` was not catching it, then this addition won't either. So most likely this particular `RuntimeError` is raised outside of this try...except statement (that's why it was uncaught). 

So this will not change anything. I would suggest making a unit test to test this case and make sure that what is fixed is actually fixed ;)

2023-03-04 18:56 UTC, InspectorCaracal commented
I see.

Since my original fix is unacceptable, I'll close this and make a new one if I figure out the correct solution.

2023-03-04 18:56 UTC, closed without merging

2023-03-04 19:12 UTC, Griatch commented
Ok! Maybe it could do with a feature-request ticket as well