Alter Global Scripts handling
evennia/evennia pull request #3197
Opened 2023-05-23 13:27 UTC by volundmush

#### Brief overview of PR changes/additions
Currently, Global Scripts are started at the end of evennia._init(), which is called by both the portal and the server. The GlobalScriptContainer is also having trouble distinguishing "scripts defined in its settings.py section" from "ALL Scripts which have no db_obj attached" and tries to start them all...

Not only that, but the scripts are starting before at_server_init() and all startup hooks are called, so they might fire off before the game has finished loading critical resources.

Even if it's running on the portal.

To combat this, I moved the GLOBAL_SCRIPTS.start() to the very end of the server startup process, after calling startup hooks.

#### Motivation for adding to Evennia
The above is definitely not something we want happening.

#### Other info (issues closed, discussion etc)

2023-05-27 08:36 UTC, Griatch requested changes
Overall, I think this looks fine. The unit tests don't pass though.

2023-06-04 07:23 UTC, Griatch commented
@volundmush Fixing the unit tests should be what remains for this PR.

2023-09-03 06:33 UTC, Griatch commented
@volundmush Ping. This and the other PRs you made often require rather small additions/unit test fixes.

2023-09-08 19:49 UTC, volundmush commented
It looks like blongden got to this first - sorry I lost my momentum there. This PR has been superseded.

2023-09-08 21:18 UTC, Griatch commented
@volundmush Not sure about that ... Blongden made a fix to make sure global scripts does not start up in the portal; I think this PR covers a different case.

2023-09-09 07:42 UTC, blongden commented
> @volundmush Not sure about that ... Blongden made a fix to make sure global scripts does not start up in the portal; I think this PR covers a different case.

Agreed. This incorporates a nicer fix to the same issue, moving the scripts start into the server rather than keeping it in init.

2023-09-20 20:51 UTC, Griatch commented
@volundmush Is this ready to re-review?

2023-10-31 19:36 UTC, Griatch approved these changes
LGTM! And unit tests pass now too :+1:

2023-10-31 19:36 UTC, merged