Breakup DefaultObject.msg() and add an at_post_msg_receive() hook
evennia/evennia pull request #3326
Opened 2023-11-09 20:17 UTC by volundmush

#### Brief overview of PR changes/additions
Pretty much exactly what it says on the tin.

This refactors DefaultObject.msg(), breaking it up to rely on a series of helper methods and adding a new hook that's called at the end of a successful message send.

#### Motivation for adding to Evennia
There is currently no way to access the finalized kwargs at the end of the .msg() call, which I wish to be able to nab for purposes of logging. Since it's a pain in the ass to reimplement/overload .msg() in general I figured out breaking it up at the same time would be a good idea.

2023-11-18 12:56 UTC, Griatch requested changes
I don't mind the `msg` method being broken up into smaller parts; I think this could be useful for devs! I have a few questions/concerns about this though before merge:  

1. Majority of these break-out methods are "private" (`_` prefix), and while this makes sense from a purely Pythonic perspective, Evennia offers and API, and in an API, private methods suggests that the API is not to be overridden by the user (because it's private it could be changed without warning upstream). Since the reason to break up `msg` would ostensibly be to make it easier to override, I'd think these sub-methods should not be private. 
2. Following the style used everywhere in Evennia, the sub-methods should appear above the method using them in the class. So please move `msg` to the end, after its helper methods.

2023-11-18 12:56 UTC, Griatch commented on evennia/objects/objects.py
> +        pass
If this is the only method intended to be overridden, it would be more visible to move it to the end of this block, after all the private methods.

2023-11-18 12:56 UTC, Griatch commented on evennia/objects/objects.py
> +        self._msg_helper_from_obj(from_obj=from_obj, **kwargs)
While I can see the point of these being private from a code perspective, using a private `_` prefix also suggests that this is a private method that is not intended to be customized by the developer.

2023-12-02 17:52 UTC, Griatch commented
@volundmush Ping.

2023-12-05 21:04 UTC, closed without merging

2023-12-05 21:04 UTC, volundmush commented
This PR is rendered completely useless by #3356 so I'm gonna retire it. Thanks for keeping up with this though.