docs(beginner tutorial unit testing): :memo: revise prose and bug-fix
evennia/evennia pull request #3364
Opened 2023-12-12 14:07 UTC by iLPdev

#### Brief overview of PR changes/additions
General prose editing for punctuation, syntax, grammar, clarity, etc. including fix for #3360.    

#### Motivation for adding to Evennia
progress, not perfection

#### Other info (issues closed, discussion etc)
closes #3360

2023-12-16 13:16 UTC, Griatch requested changes
Good stuff! Just some remaining spelling errors/typos.

2023-12-16 13:16 UTC, Griatch commented on docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Utilities.md
> +Using enums is a recommended practice. With enums set up, we can make sure to refer to the same contant or variable every time. Keeping all enums in one place also means we have a good overview of th
contant->constant

2023-12-16 13:16 UTC, Griatch commented on docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Utilities.md
> +
than->then

2023-12-16 13:16 UTC, Griatch commented on docs/source/Howtos/Beginner-Tutorial/Part3/Beginner-Tutorial-Utilities.md
> +Doing so should spit back a nice bit of string ouput about yourself! If that works, great! But, you'll need to remember re-running that test mannually when you later change the code.
mannually -> manually

2023-12-21 12:36 UTC, iLPdev commented
nice catches!!

2024-01-08 18:39 UTC, Griatch requested changes
Thanks for correcting! Seems there is a merge conflict (upstream likely updated slightly and changes a string in the same place); just fix that and we can merge :)

2024-01-28 13:27 UTC, Griatch commented
Ping. This just needs a rebase.

2024-02-24 08:14 UTC, Griatch commented
Another ping.

2024-03-08 08:03 UTC, merged

2024-03-08 08:05 UTC, Griatch commented
Resolved merge conflict and merged this one since it's been hanging around for a long time.