Fix editor echo not displaying correctly for lines with whitespace
evennia/evennia pull request #3459
Opened 2024-03-30 14:32 UTC by chiizujin

#### Brief overview of PR changes/additions

When in normal editing mode (i.e. not in code editing mode) and adding lines with extra whitespace (leading or between words) the input echoing does not correctly reflect what is actually added to the buffer (the extra space is stripped).

This fixes the echo to correctly show what is added.

#### Motivation for adding to Evennia

Correct editor echo display.

#### Other info

**Before (in the editor):**
```
>  This  line   has    whitespace.
01| This line has whitespace.
>:
----------Line Editor [topic test]--------------------------------------------
01|   This  line   has    whitespace.
----------[l:01 w:004 c:0033]------------(:h for help)------------------------
```
**After (in the editor):**
```
>  This  line   has    whitespace.
01|   This  line   has    whitespace.
>:
----------Line Editor [topic test]--------------------------------------------
01|   This  line   has    whitespace.
----------[l:01 w:004 c:0033]------------(:h for help)------------------------
```

2024-03-30 14:56 UTC, Griatch requested changes
Good catch! I agree with the fix, but I think this is also a good opportunity to add a new test to make sure to test this case and make sure to avoid regressions in the future.

2024-03-30 14:56 UTC, Griatch commented on evennia/utils/tests/test_eveditor.py
> +            msg="02Second 'line'.",
It seems like a good opportunity to actually add a new test here to verify the echo is indeed as expected?

2024-03-31 01:07 UTC, chiizujin commented
I've added a unit test for this. I added it the end of the editor tests so that the addition of another line doesn't break the tests that rely on the buffer content.

2024-04-01 08:13 UTC, Griatch approved these changes
New test seems fine, thanks for adding it!

2024-04-01 08:13 UTC, merged