Add width argument to editor's :j and :f commands
evennia/evennia pull request #3497
Opened 2024-04-08 04:34 UTC by chiizujin

#### Brief overview of PR changes/additions

Adds the ability to optionally specify a width for the editor's `:j` and `:f` commands. Changes `<w>` (alignment) to `<a>` in help so that `<w>` can be used to represent width.

A new syntax element (`=`) had to be introduced to prevent a clash between the numeric arguments `<l>` and `<w>` when some arguments are omitted (e.g. does `:j 10` mean 'justify line 10' or 'justify to width 10'?)

#### Motivation for adding to Evennia

New feature.

#### Other info
```
>:
----------Line Editor [topic test]--------------------------------------------
01| A long line of text to test the editor's justification command with a custom
width.
----------[l:01 w:015 c:0083]------------(:h for help)------------------------
```
```
>:j
Full-justified lines 1-1.
>:
----------Line Editor [topic test]--------------------------------------------
01| A  long  line of text to test the editor's justification command with a custom
02| width.
----------[l:02 w:015 c:0085]------------(:h for help)------------------------
```
```
>:j =40
Full-justified lines 1-2.
>:
----------Line Editor [topic test]--------------------------------------------
01| A long line of text to test the editor's
02| justification   command  with  a  custom
03| width.
----------[l:03 w:015 c:0088]------------(:h for help)------------------------
```
```
>:j r =40
Right-justified lines 1-3.
>:
----------Line Editor [topic test]--------------------------------------------
01| A long line of text to test the editor's
02|      justification command with a custom
03|                                   width.
----------[l:03 w:015 c:0122]------------(:h for help)------------------------
```
```
>:j 1:2 l =60
Left-justified lines 1-2.
>:
----------Line Editor [topic test]--------------------------------------------
01| A long line of text to test the editor's justification      
02| command with a custom                                       
03|                                   width.
----------[l:03 w:015 c:0162]------------(:h for help)------------------------
```
```
>:f =30
Flood filled lines 1-3.
>:
----------Line Editor [topic test]--------------------------------------------
01| A long line of text to test
02| the editor's justification
03| command with a custom
04| width.
----------[l:04 w:015 c:0083]------------(:h for help)------------------------
```

2024-04-27 16:55 UTC, Griatch requested changes
I think this is a useful change, but I don't think it should be done in a backwards-incompatible way. See comment.

2024-04-27 16:55 UTC, Griatch commented on evennia/utils/eveditor.py
> +                    Equivalent to :j <l> l
This is a backwards-incompatible change. I think we could just as well retain the old functionality as a default: 

```
:j <l> <a>  - working as before (fixed width, just change `<w>` to `<a>`)
:j <l> <a> = <w>  - using the = to show that we are introducing a width 
:f <l> - default flood fill
:f <l> = <w> - flood fill with width
```

2024-04-28 02:22 UTC, chiizujin commented
`<w>` is already optional for both and if not provided they behave as the old functionality so it doesn't change the current behaviour of `:j <l> <a>` (calling it `a` here to be clear) and `:f <l>`. Unless I've misunderstood what you meant.

I've updated the help text to clarify this.

2024-06-14 07:37 UTC, Griatch approved these changes
Ok, approved! (and sorry for the delay)

2024-06-14 07:37 UTC, merged